
== Использование с Klipper

Установку лучше всего делать с помощью установщика https://github.com/dw-0/kiauh[KIAUH].

Для максимальной производительности надо заменить установленный с помощью KIAUH klipper на форк из https://github.com/tntclaus/klipper[tntclaus/klipper] с поддержкой аппаратного ускорения gpio на RPi. Если установить из основного репозитория, gpio будет очень медленным и использовать все преимущества контроллеров не выйдет.

.Команды для замены репозитория на форк
[source]
----
# Выполнять от пользователя pi
cd ~
rm -Rf klipper
git clone -b work-linux-rpi-gpio-20210419 --single-branch git@github.com:tntclaus/klipper.git
----

Далее установка и сборка mcu Klipper делается по https://www.klipper3d.org/RPi_microcontroller.html[стандартной процедуре].

NOTE: В меню конфигурации, при вызове `make menuconfig` надо выбрать тип "Microcontroller Architecture" — "Linux Process", затем выбрать модель Raspberry.

Кроме того, надо в `/boot/cmdline.txt` распберри дописать в конце строки `isolcpus=3` — это запретит линуксу назначать на ядро под номером три какие-либо процессы, кроме тех, для которых оно задано явным образом в стартовом скрипте. Данное ядро будет использоваться процессом `klipper_mcu`.

NOTE: WiFi на Raspberry использовать нельзя, так как это может приводить к блокированию процесса `klipper_mcu` и сбоям при работе станка.

После установки требуется сконфигурировать klipper так, чтобы он мог работать с драйверами шаговых двигателей. Описание того какие gpio за что отвечают есть на страницах соответствующих моделей шилдов.
